/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExchangeAdapterV3,
  IExchangeAdapterV3Interface,
} from "../IExchangeAdapterV3";

const _abi = [
  {
    inputs: [],
    name: "getSpender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_sourceToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_destinationToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_destinationAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_exactQuantity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_edgedQuantity",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_shouldSwapExactTokensForTokens",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "getTradeCalldata",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExchangeAdapterV3__factory {
  static readonly abi = _abi;
  static createInterface(): IExchangeAdapterV3Interface {
    return new utils.Interface(_abi) as IExchangeAdapterV3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExchangeAdapterV3 {
    return new Contract(address, _abi, signerOrProvider) as IExchangeAdapterV3;
  }
}
