/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IManagerIssuanceHook,
  IManagerIssuanceHookInterface,
} from "../IManagerIssuanceHook";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_issueQuantity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "invokePreIssueHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_redeemQuantity",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "invokePreRedeemHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IManagerIssuanceHook__factory {
  static readonly abi = _abi;
  static createInterface(): IManagerIssuanceHookInterface {
    return new utils.Interface(_abi) as IManagerIssuanceHookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IManagerIssuanceHook {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IManagerIssuanceHook;
  }
}
