/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IModule, IModuleInterface } from "../IModule";

const _abi = [
  {
    inputs: [],
    name: "removeModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IModule__factory {
  static readonly abi = _abi;
  static createInterface(): IModuleInterface {
    return new utils.Interface(_abi) as IModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IModule {
    return new Contract(address, _abi, signerOrProvider) as IModule;
  }
}
