/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISetValuer, ISetValuerInterface } from "../ISetValuer";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_quoteAsset",
        type: "address",
      },
    ],
    name: "calculateSetTokenValuation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISetValuer__factory {
  static readonly abi = _abi;
  static createInterface(): ISetValuerInterface {
    return new utils.Interface(_abi) as ISetValuerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISetValuer {
    return new Contract(address, _abi, signerOrProvider) as ISetValuer;
  }
}
