/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IXERC20, IXERC20Interface } from "../IXERC20";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IXERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IXERC20Interface {
    return new utils.Interface(_abi) as IXERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IXERC20 {
    return new Contract(address, _abi, signerOrProvider) as IXERC20;
  }
}
