/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IExchangeAdapterV3Interface extends utils.Interface {
  contractName: "IExchangeAdapterV3";
  functions: {
    "getSpender()": FunctionFragment;
    "getTradeCalldata(address,address,address,uint256,uint256,bool,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSpender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeCalldata",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getSpender", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTradeCalldata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IExchangeAdapterV3 extends BaseContract {
  contractName: "IExchangeAdapterV3";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IExchangeAdapterV3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSpender(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTradeCalldata(
      _sourceToken: string,
      _destinationToken: string,
      _destinationAddress: string,
      _exactQuantity: BigNumberish,
      _edgedQuantity: BigNumberish,
      _shouldSwapExactTokensForTokens: boolean,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getSpender(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTradeCalldata(
    _sourceToken: string,
    _destinationToken: string,
    _destinationAddress: string,
    _exactQuantity: BigNumberish,
    _edgedQuantity: BigNumberish,
    _shouldSwapExactTokensForTokens: boolean,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getSpender(overrides?: CallOverrides): Promise<string>;

    getTradeCalldata(
      _sourceToken: string,
      _destinationToken: string,
      _destinationAddress: string,
      _exactQuantity: BigNumberish,
      _edgedQuantity: BigNumberish,
      _shouldSwapExactTokensForTokens: boolean,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;
  };

  filters: {};

  estimateGas: {
    getSpender(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTradeCalldata(
      _sourceToken: string,
      _destinationToken: string,
      _destinationAddress: string,
      _exactQuantity: BigNumberish,
      _edgedQuantity: BigNumberish,
      _shouldSwapExactTokensForTokens: boolean,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSpender(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTradeCalldata(
      _sourceToken: string,
      _destinationToken: string,
      _destinationAddress: string,
      _exactQuantity: BigNumberish,
      _edgedQuantity: BigNumberish,
      _shouldSwapExactTokensForTokens: boolean,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
