/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IIntegrationRegistryInterface extends utils.Interface {
  contractName: "IIntegrationRegistry";
  functions: {
    "addIntegration(address,string,address)": FunctionFragment;
    "getIntegrationAdapter(address,string)": FunctionFragment;
    "getIntegrationAdapterWithHash(address,bytes32)": FunctionFragment;
    "isValidIntegration(address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addIntegration",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntegrationAdapter",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntegrationAdapterWithHash",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidIntegration",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addIntegration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntegrationAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntegrationAdapterWithHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidIntegration",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IIntegrationRegistry extends BaseContract {
  contractName: "IIntegrationRegistry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IIntegrationRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addIntegration(
      _module: string,
      _id: string,
      _wrapper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getIntegrationAdapter(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getIntegrationAdapterWithHash(
      _module: string,
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isValidIntegration(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  addIntegration(
    _module: string,
    _id: string,
    _wrapper: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getIntegrationAdapter(
    _module: string,
    _id: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getIntegrationAdapterWithHash(
    _module: string,
    _id: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  isValidIntegration(
    _module: string,
    _id: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    addIntegration(
      _module: string,
      _id: string,
      _wrapper: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getIntegrationAdapter(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getIntegrationAdapterWithHash(
      _module: string,
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    isValidIntegration(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addIntegration(
      _module: string,
      _id: string,
      _wrapper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getIntegrationAdapter(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntegrationAdapterWithHash(
      _module: string,
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidIntegration(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addIntegration(
      _module: string,
      _id: string,
      _wrapper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getIntegrationAdapter(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntegrationAdapterWithHash(
      _module: string,
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidIntegration(
      _module: string,
      _id: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
