/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IManagerIssuanceHookInterface extends utils.Interface {
  contractName: "IManagerIssuanceHook";
  functions: {
    "invokePreIssueHook(address,uint256,address,address)": FunctionFragment;
    "invokePreRedeemHook(address,uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "invokePreIssueHook",
    values: [string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "invokePreRedeemHook",
    values: [string, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "invokePreIssueHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invokePreRedeemHook",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IManagerIssuanceHook extends BaseContract {
  contractName: "IManagerIssuanceHook";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IManagerIssuanceHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    invokePreIssueHook(
      _setToken: string,
      _issueQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invokePreRedeemHook(
      _setToken: string,
      _redeemQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  invokePreIssueHook(
    _setToken: string,
    _issueQuantity: BigNumberish,
    _sender: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invokePreRedeemHook(
    _setToken: string,
    _redeemQuantity: BigNumberish,
    _sender: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    invokePreIssueHook(
      _setToken: string,
      _issueQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    invokePreRedeemHook(
      _setToken: string,
      _redeemQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    invokePreIssueHook(
      _setToken: string,
      _issueQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invokePreRedeemHook(
      _setToken: string,
      _redeemQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    invokePreIssueHook(
      _setToken: string,
      _issueQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invokePreRedeemHook(
      _setToken: string,
      _redeemQuantity: BigNumberish,
      _sender: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
